language: python

python:
  - "3.6"


install:
  - pip install pipenv
  - pipenv install
  - pipenv install requests

services:
  - postgresql


before_script:
  - psql -c "CREATE DATABASE sniffy;" -U postgres


script:
  - pytest
